# Local Kafka Connect worker example configured to talk to Kafka using SASL_SSL.

bootstrap.servers=localhost:9093
group.id=connect-secure-cluster
config.storage.topic=_connect-secure-configs
offset.storage.topic=_connect-secure-offsets
status.storage.topic=_connect-secure-status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false

plugin.path=/usr/share/java,/usr/share/confluent-hub-components
rest.port=8083
rest.advertised.host.name=localhost

security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
ssl.truststore.location=/etc/kafka/secrets/client.truststore.jks
ssl.truststore.password=changeit

producer.security.protocol=SASL_SSL
producer.sasl.mechanism=PLAIN
producer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
producer.ssl.truststore.location=/etc/kafka/secrets/client.truststore.jks
producer.ssl.truststore.password=changeit

consumer.security.protocol=SASL_SSL
consumer.sasl.mechanism=PLAIN
consumer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
consumer.ssl.truststore.location=/etc/kafka/secrets/client.truststore.jks
consumer.ssl.truststore.password=changeit

admin.security.protocol=SASL_SSL
admin.sasl.mechanism=PLAIN
admin.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
admin.ssl.truststore.location=/etc/kafka/secrets/client.truststore.jks
admin.ssl.truststore.password=changeit