# Local ksqlDB server example configured to talk to Kafka using SASL_SSL.

bootstrap.servers=localhost:9093
listeners=http://0.0.0.0:8088
ksql.service.id=ksql-secure-local_

security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
ssl.truststore.location=/etc/kafka/secrets/client.truststore.jks
ssl.truststore.password=changeit

ksql.schema.registry.url=http://schema-registry:8081
ksql.connect.url=http://connect:8083
ksql.logging.processing.topic.replication.factor=1
ksql.logging.processing.topic.auto.create=true
ksql.logging.processing.stream.auto.create=true