# Local Schema Registry example configured to talk to Kafka using SASL_SSL.
# Listener security for Schema Registry itself is left simple here to keep focus on Kafka connectivity.

listeners=http://0.0.0.0:8081
host.name=localhost

kafkastore.bootstrap.servers=SASL_SSL://localhost:9093
kafkastore.security.protocol=SASL_SSL
kafkastore.sasl.mechanism=PLAIN
kafkastore.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
kafkastore.ssl.truststore.location=/etc/kafka/secrets/client.truststore.jks
kafkastore.ssl.truststore.password=changeit

schema.compatibility.level=BACKWARD