KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="broker"
  password="broker-secret"
  user_broker="broker-secret"
  user_admin="admin-secret"
  user_appuser="app-secret";
};