apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  namespace: confluent
data:
  flink-conf.yaml: |+
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 2
    blob.server.port: 6124
    jobmanager.rpc.port: 6123
    taskmanager.rpc.port: 6122
    queryable-state.proxy.ports: 6125
    jobmanager.memory.process.size: 1600m
    taskmanager.memory.process.size: 1728m
    parallelism.default: 1
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: confluent
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob
    port: 6124
  - name: ui
    port: 8081
  selector:
    app: flink
    component: jobmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      initContainers:
      - name: fetch-connectors
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - |
          curl -sSL https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.1.0-1.18/flink-sql-connector-kafka-3.1.0-1.18.jar -o /target-lib/flink-sql-connector-kafka.jar
        volumeMounts:
        - name: extra-lib
          mountPath: /target-lib
      containers:
      - name: jobmanager
        image: apache/flink:1.19.0-scala_2.12-java17
        args: ["jobmanager"]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 8081
          name: ui
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        - name: extra-lib
          mountPath: /opt/flink/lib/flink-sql-connector-kafka.jar
          subPath: flink-sql-connector-kafka.jar
      volumes:
      - name: extra-lib
        emptyDir: {}
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      initContainers:
      - name: fetch-connectors
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - |
          curl -sSL https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.1.0-1.18/flink-sql-connector-kafka-3.1.0-1.18.jar -o /target-lib/flink-sql-connector-kafka.jar
        volumeMounts:
        - name: extra-lib
          mountPath: /target-lib
      containers:
      - name: taskmanager
        image: apache/flink:1.19.0-scala_2.12-java17
        args: ["taskmanager"]
        ports:
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query-state
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        - name: extra-lib
          mountPath: /opt/flink/lib/flink-sql-connector-kafka.jar
          subPath: flink-sql-connector-kafka.jar
      volumes:
      - name: extra-lib
        emptyDir: {}
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
